<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( '_id',
'account_id',
'failed',
'asset_id',
'destination_id',
'device_id',
'product_series_id',
'created',
'create_at' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( '_id' => array( 'import_field' ),
'account_id' => array( 'import_field1' ),
'asset_id' => array( 'import_field2' ),
'product_series_id' => array( 'import_field3' ),
'failed' => array( 'import_field4' ),
'destination_id' => array( 'import_field5' ),
'device_id' => array( 'import_field6' ),
'created' => array( 'import_field7' ),
'create_at' => array( 'import_field8' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field4',
'import_field2',
'import_field5',
'import_field6',
'import_field3',
'import_field7',
'import_field8' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field4' => 'grid',
'import_field2' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field3' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8' ) ),
'cellMaps' => array(  ) ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field4',
'import_field2',
'import_field5',
'import_field6',
'import_field3',
'import_field7',
'import_field8' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => '_id',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'account_id',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'asset_id',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'product_series_id',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'failed',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'destination_id',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'device_id',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'created',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'create_at',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>