<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( '_id',
'account_id',
'_index',
'_type',
'invited_id',
'email',
'invite_at',
'expire_at',
'magiclink',
'accept_at',
'finish_at',
'contact_id',
'update_at' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( '_id' => array( 'import_field' ),
'account_id' => array( 'import_field1' ),
'_index' => array( 'import_field2' ),
'_type' => array( 'import_field3' ),
'invited_id' => array( 'import_field4' ),
'email' => array( 'import_field5' ),
'invite_at' => array( 'import_field6' ),
'expire_at' => array( 'import_field7' ),
'magiclink' => array( 'import_field8' ),
'accept_at' => array( 'import_field9' ),
'finish_at' => array( 'import_field10' ),
'contact_id' => array( 'import_field11' ),
'update_at' => array( 'import_field12' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12' ) ),
'cellMaps' => array(  ) ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => '_id',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'account_id',
'type' => 'import_field' ),
'import_field2' => array( 'field' => '_index',
'type' => 'import_field' ),
'import_field3' => array( 'field' => '_type',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'invited_id',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'email',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'invite_at',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'expire_at',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'magiclink',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'accept_at',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'finish_at',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'contact_id',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'update_at',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>